//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityLife.DALImplementation {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Root")]
        public string AppRole_Root {
            get {
                return ((string)(this["AppRole_Root"]));
            }
            set {
                this["AppRole_Root"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Administrator")]
        public string AppRole_Administrator {
            get {
                return ((string)(this["AppRole_Administrator"]));
            }
            set {
                this["AppRole_Administrator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Moderator")]
        public string AppRole_Moderator {
            get {
                return ((string)(this["AppRole_Moderator"]));
            }
            set {
                this["AppRole_Moderator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("User")]
        public string AppRole_User {
            get {
                return ((string)(this["AppRole_User"]));
            }
            set {
                this["AppRole_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kamcitylife@yandex.ru")]
        public string AppUser_Root_Name {
            get {
                return ((string)(this["AppUser_Root_Name"]));
            }
            set {
                this["AppUser_Root_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kamcitylife@yandex.ru")]
        public string AppUser_Root_Email {
            get {
                return ((string)(this["AppUser_Root_Email"]));
            }
            set {
                this["AppUser_Root_Email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a!sads0185%!Sasd")]
        public string AppUser_Root_Password {
            get {
                return ((string)(this["AppUser_Root_Password"]));
            }
            set {
                this["AppUser_Root_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Organization")]
        public string AppRole_Organization {
            get {
                return ((string)(this["AppRole_Organization"]));
            }
            set {
                this["AppRole_Organization"] = value;
            }
        }
    }
}
